

include:
  - proxy.yaml

volumes:
  db_mysql:

services:

  db:
    image: mysql:8
    restart: on-failure
    env_file:
      - .env
    volumes:
      - /var/lib/docker/volumes/db_mysql/_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      backend:
        ipv4_address: 172.20.0.10

  web:
    build:
          dockerfile: Dockerfile.python
    restart: on-failure
    env_file:
      - .env  # Подключаем файл .env
    environment:
      - DB_HOST=db
      - DB_USER=${MYSQL_USER}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db
    ports:
      - 5000:5000
    networks:
      backend:
        ipv4_address: 172.20.0.5